// <auto-generated />
namespace IT_self_service_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class from1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(from1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712201301380_from1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
